version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - postgres
        networks:
            - crm_backend

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - crm_backend

    postgres:
        image: postgres:15
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - "5432:5432"
        networks:
            - crm_backend

    queue:
        build:
            context: docker/queue
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - crm_backend
    # redis
    redis:
        image: redis:latest
        networks:
            - crm_backend

volumes:
  postgres_data:            
    driver: local

networks:
    crm_backend:
        driver: bridge
